export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_ERROR = 'CATEGORY_LIST_ERROR';

export const GET_PRODUCT_DETAILS_REQUEST = 'GET_PRODUCT_DETAILS_REQUEST';
export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS';
export const GET_PRODUCT_DETAILS_ERROR = 'GET_PRODUCT_DETAILS_ERROR';

export const GET_PRODUCT_DETAILS_BY_ID_REQUEST = 'GET_PRODUCT_DETAILS_BY_ID_REQUEST';
export const GET_PRODUCT_DETAILS_BY_ID_SUCCESS = 'GET_PRODUCT_DETAILS_BY_ID_SUCCESS';
export const GET_PRODUCT_DETAILS_BY_ID_ERROR = 'GET_PRODUCT_DETAILS_BY_ID_ERROR';
